version = 0.1

[default.build.parameters]
use_container = true

[default.deploy.parameters]
stack_name = "ai-news-curator-lite"
resolve_s3 = true
s3_prefix = "ai-news-curator-lite"
region = "ap-northeast-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []

[default.global.parameters]
region = "ap-northeast-2"
